# Generated by Django 5.1 on 2024-08-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shortener_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aliasedurl",
            name="alias",
            field=models.SlugField(unique=True),
        ),
    ]
