# Generated by Django 5.1 on 2024-08-11 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shortener_app", "0002_alter_aliasedurl_alias"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aliasedurl",
            name="alias",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
